# example netlify.toml
[build]
  command = "yarn run build"
  functions = "netlify/functions"
  publish = "app"

[build.environment]
  YARN = "true"

# Uncomment the redirects section if you need it.
#[[redirects]]
#  from = "/*"
#  to = "/index.html"
#  status = 200

# Uncomment the dev section if you need to configure Netlify Dev.
#[dev]
#  command = "yarn start" # Command to start your dev server
#  port = 3000 # Port that the dev server will be listening on
#  publish = "dist" # Folder with the static content for _redirect file

  ## more info on configuring this file: https://docs.netlify.com/configure-builds/file-based-configuration/
